In [184]:
import sys
import time
sys.path.append('/Applications/Data/anaconda/pkgs/requests-2.13.0-py27_0/lib/python2.7/site-packages')

import requests
from BeautifulSoup import BeautifulSoup
Soup = BeautifulSoup
import re
import csv
import pandas as pd
import datetime
import urllib2
import time
import collections
from collections import Counter
import nltk

In [185]:
words  = []
strings = []
desc = pd.read_excel('NFPdescriptions1.xlsx')

#cleansup url descrioptions and pulls out the nouns


for i in range(0,135):
    string = str(desc[0][i])
    string1 = (re.sub('<.+?>', '', string))
    string2 = (re.sub('&middot;', '', string1))
    string3 = (re.sub('&amp;', '', string2))
    string4 = (re.sub('&nbsp;', '', string3))
    string5 = (re.sub('[A-Z0-9].*com', '', string4))
    string6 = (re.sub('&#39', '', string5))
    strings.append(string6)

for i in range(0,135):    
    desc_df = pd.DataFrame(strings)
    a = desc_df[0][i].split()
    words.append(a)

                                #count = []    
                                #for x in range(0,52):
                                #    c1 = Counter(words[x])
                                #    count.append(c1)

                                #nouns = []   
                                #for j in range(0,135):
                                #    tagged = nltk.pos_tag(words[j])
                                #    noun = [word for word, pos in tagged if pos == 'PRT']
                                #    nouns.append(noun)
                                    #count[1]
                                    #return nouns

                                #cleansup = []
                                #cleansup.append(cleanup(desc))
                                #cleansup
                                #words

                                #if del_phrase[1] in words[0]:
                                #    print "success"
                                #else: print "false"
    

words_df = pd.DataFrame(words)
writer = pd.ExcelWriter('NFPwords1.xlsx', engine = 'xlsxwriter')
words_df.to_excel(writer, sheet_name = 'Descriptions')
writer.save()

In [186]:
# Levenshtein Distance
def levenshtein(s1, s2):
    if len(s1) < len(s2):
        return levenshtein(s2, s1)

    # len(s1) >= len(s2)
    if len(s2) == 0:
        return len(s1)

    previous_row = range(len(s2) + 1)
    for i, c1 in enumerate(s1):
        current_row = [i + 1]
        for j, c2 in enumerate(s2):
            insertions = previous_row[j + 1] + 1 # j+1 instead of j since previous_row and current_row are one character longer
            deletions = current_row[j] + 1       # than s2
            substitutions = previous_row[j] + (c1 != c2)
            current_row.append(min(insertions, deletions, substitutions))
        previous_row = current_row
    
    return previous_row[-1]

s = 'tech'
s0 = 'technology'
levenshtein(s,s0)

6

In [187]:
general = ('weather', 'entertainment', 'health', 'science', 'Politics', 'headlines');
sports = ('sport', 'sports', 'scores');
insurance = ('Underwriter','property and casualty', 'property', 'casualty', 'insurance', 'agents', 'brokerage', 'retirement', 'tax', 'estate planning', 'mortgage');
finance = ('finance', 'financial', 'stock', 'risk', 'market', 'markets', 'investing', 'money');
tech = ('tech', 'technology');
data = ('data', 'analytics', 'analysis');

In [188]:
# Gets list of all types

tag = []
insurance_count = 0
general_count = 0
sports_count = 0
finance_count = 0
tech_count = 0
data_count = 0

for i in range (0, len(insurance)):
    for j in range (0, 135):
        if insurance[i] in words[j]:
            insurance_count += 1

for i in range (0, len(finance)):
    for j in range (0, 135):
        if finance[i] in words[j]:
            finance_count += 1
            
for i in range (0, len(general)):
    for j in range (0, 135):
        if general[i] in words[j]:
            general_count += 1
            
for i in range (0, len(sports)):
    for j in range (0, 135):
        if sports[i] in words[j]:
            sports_count += 1
            
for i in range (0, len(tech)):
    for j in range (0, 135):
        if tech[i] in words[j]:
            tech_count += 1
            
for i in range (0, len(data)):
    for j in range (0, 135):
        if data[i] in words[j]:
            data_count += 1

tag.append(insurance_count) 
tag.append(finance_count)
tag.append(general_count)
tag.append(sports_count)
tag.append(tech_count)
tag.append(data_count)

tag

[22, 39, 13, 7, 7, 18]

In [189]:
# % breakdown for publication type

tag = []
percent = []


def classify(industry):
    for i in range (0, 135):
        count = 0
        for j in range(0,len(words[i])):
            for k in range (0, len(industry)):
                if industry[k] in words[i][j]:
                    count += 1                    
        tag.append(count)
        percent.append((float(tag[i])/(len(words[i])))*100 )   


    
#classifying for general url's
classify(general)
generalpc = pd.DataFrame()
generalpc_df = generalpc.append(percent)
generalpc_df

tag = []
percent = []

#classifying for finance url's
classify(finance)
financepc = pd.DataFrame()
financepc_df = financepc.append(percent)
financepc_df

tag = []
percent = []

#classifying for insurance url's
classify(insurance)
insurancepc = pd.DataFrame()
insurancepc_df = insurancepc.append(percent)
insurancepc_df

tag = []
percent = []

#classifying for sports url's
classify(sports)
sportspc = pd.DataFrame()
sportspc_df = sportspc.append(percent)
sportspc_df

result = pd.concat([generalpc_df, financepc_df, insurancepc_df, sportspc_df ], axis = 1)
result.columns = ['General', 'Finance', 'Insurance', 'Sports']
result

       General    Finance  Insurance     Sports
0     0.000000   0.000000  25.000000   0.000000
1    30.769231   0.000000   0.000000   0.000000
2     5.000000   0.000000   0.000000   0.000000
3    16.666667   0.000000   0.000000   0.000000
4     0.000000   0.000000   7.692308   0.000000
5     0.000000   0.000000   0.000000   0.000000
6     5.000000   5.000000   0.000000  10.000000
7     0.000000   0.000000   0.000000   0.000000
8     0.000000   0.000000  13.043478   0.000000
9     0.000000   0.000000   0.000000   0.000000
10    0.000000  33.333333   0.000000   0.000000
11    0.000000   0.000000   0.000000   0.000000
12    0.000000   0.000000   5.882353   0.000000
13    5.000000   0.000000   0.000000   0.000000
14    0.000000   5.263158   0.000000   0.000000
15    0.000000   0.000000   0.000000   0.000000
16    0.000000   0.000000   0.000000   0.000000
17    6.250000   0.000000   6.250000   0.000000
18    4.166667   0.000000   0.000000   0.000000
19    0.000000  10.000000   0.000000   0.000000
20    4.761905   9.523810   0.000000   0.000000
21    0.000000   0.000000   0.000000   0.000000
22    0.000000  10.000000   5.000000   0.000000
23    0.000000   0.000000   0.000000   0.000000
24    0.000000   7.407407   0.000000   0.000000
25    0.000000   0.000000   0.000000   0.000000
26    0.000000   0.000000   0.000000   7.692308
27    0.000000   0.000000   0.000000   0.000000
28    0.000000   0.000000   0.000000   0.000000
29    0.000000   0.000000   0.000000   0.000000
..         ...        ...        ...        ...
105   0.000000   0.000000   0.000000   0.000000
106   0.000000   0.000000   0.000000   0.000000
107   3.846154   0.000000   0.000000   0.000000
108   5.882353   0.000000   0.000000  11.764706
109  10.526316   0.000000   0.000000   0.000000
110   4.166667   0.000000   0.000000   8.333333
111   0.000000   0.000000   0.000000   0.000000
112   0.000000   0.000000   0.000000   0.000000
113   0.000000   9.090909   9.090909   0.000000
114  11.111111   0.000000   0.000000  11.111111
115   0.000000   0.000000   0.000000   0.000000
116   0.000000   0.000000   0.000000   0.000000
117   4.545455   0.000000   0.000000   0.000000
118   0.000000   0.000000   0.000000   0.000000
119   4.000000   0.000000   0.000000   8.000000
120   6.666667   0.000000   0.000000   0.000000
121   0.000000   0.000000   0.000000   0.000000
122   0.000000   0.000000   0.000000   0.000000
123   0.000000   0.000000   0.000000   0.000000
124   0.000000   7.142857   0.000000   0.000000
125   4.166667   0.000000   0.000000   0.000000
126   0.000000   0.000000   0.000000   0.000000
127   0.000000   0.000000   0.000000   0.000000
128   0.000000   0.000000   0.000000   4.166667
129   0.000000   0.000000   0.000000   0.000000
130   0.000000   0.000000   0.000000   0.000000
131   4.166667   0.000000   0.000000   8.333333
132   5.555556   0.000000   0.000000  11.111111
133   0.000000   0.000000   0.000000  13.043478
134   0.000000   0.000000   0.000000   0.000000

[135 rows x 4 columns]